In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [5]:
import seaborn as sns

In [6]:
from google.colab import files
uploaded=files.upload()

Saving Salaries (1).csv to Salaries (1).csv

In [7]:
df=pd.read_csv('Salaries (1).csv')

In [8]:
df

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [10]:
df['salary'].dtype

dtype('int64')

In [11]:
df['rank'].dtype

dtype('O')

In [12]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [14]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [15]:
df.tail()

         rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [17]:
# attributes

In [18]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [19]:
df.size

468

In [20]:
df.shape

(78, 6)

In [21]:
df.ndim

2

In [24]:
df.values

array([['Prof', 'B', 56, 49, 'Male', 186960],
       ['Prof', 'A', 12, 6, 'Male', 93000],
       ['Prof', 'A', 23, 20, 'Male', 110515],
       ['Prof', 'A', 40, 31, 'Male', 131205],
       ['Prof', 'B', 20, 18, 'Male', 104800],
       ['Prof', 'A', 20, 20, 'Male', 122400],
       ['AssocProf', 'A', 20, 17, 'Male', 81285],
       ['Prof', 'A', 18, 18, 'Male', 126300],
       ['Prof', 'A', 29, 19, 'Male', 94350],
       ['Prof', 'A', 51, 51, 'Male', 57800],
       ['Prof', 'B', 39, 33, 'Male', 128250],
       ['Prof', 'B', 23, 23, 'Male', 134778],
       ['AsstProf', 'B', 1, 0, 'Male', 88000],
       ['Prof', 'B', 35, 33, 'Male', 162200],
       ['Prof', 'B', 25, 19, 'Male', 153750],
       ['Prof', 'B', 17, 3, 'Male', 150480],
       ['AsstProf', 'B', 8, 3, 'Male', 75044],
       ['AsstProf', 'B', 4, 0, 'Male', 92000],
       ['Prof', 'A', 19, 7, 'Male', 107300],
       ['Prof', 'A', 29, 27, 'Male', 150500],
       ['AsstProf', 'B', 4, 4, 'Male', 92000],
       ['Prof', 'A', 33, 30, 'Male', 103106],
       ['AsstProf', 'A', 4, 2, 'Male', 73000],
       ['AsstProf', 'A', 2, 0, 'Male', 85000],
       ['Prof', 'A', 30, 23, 'Male', 91100],
       ['Prof', 'B', 35, 31, 'Male', 99418],
       ['Prof', 'A', 38, 19, 'Male', 148750],
       ['Prof', 'A', 45, 43, 'Male', 155865],
       ['AsstProf', 'B', 7, 2, 'Male', 91300],
       ['Prof', 'B', 21, 20, 'Male', 123683],
       ['AssocProf', 'B', 9, 7, 'Male', 107008],
       ['Prof', 'B', 22, 21, 'Male', 155750],
       ['Prof', 'A', 27, 19, 'Male', 103275],
       ['Prof', 'B', 18, 18, 'Male', 120000],
       ['AssocProf', 'B', 12, 8, 'Male', 119800],
       ['Prof', 'B', 28, 23, 'Male', 126933],
       ['Prof', 'B', 45, 45, 'Male', 146856],
       ['Prof', 'A', 20, 8, 'Male', 102000],
       ['AsstProf', 'B', 4, 3, 'Male', 91000],
       ['Prof', 'B', 18, 18, 'Female', 129000],
       ['Prof', 'A', 39, 36, 'Female', 137000],
       ['AssocProf', 'A', 13, 8, 'Female', 74830],
       ['AsstProf', 'B', 4, 2, 'Female', 80225],
       ['AsstProf', 'B', 5, 0, 'Female', 77000],
       ['Prof', 'B', 23, 19, 'Female', 151768],
       ['Prof', 'B', 25, 25, 'Female', 140096],
       ['AsstProf', 'B', 11, 3, 'Female', 74692],
       ['AssocProf', 'B', 11, 11, 'Female', 103613],
       ['Prof', 'B', 17, 17, 'Female', 111512],
       ['Prof', 'B', 17, 18, 'Female', 122960],
       ['AsstProf', 'B', 10, 5, 'Female', 97032],
       ['Prof', 'B', 20, 14, 'Female', 127512],
       ['Prof', 'A', 12, 0, 'Female', 105000],
       ['AsstProf', 'A', 5, 3, 'Female', 73500],
       ['AssocProf', 'A', 25, 22, 'Female', 62884],
       ['AsstProf', 'A', 2, 0, 'Female', 72500],
       ['AssocProf', 'A', 10, 8, 'Female', 77500],
       ['AsstProf', 'A', 3, 1, 'Female', 72500],
       ['Prof', 'B', 36, 26, 'Female', 144651],
       ['AssocProf', 'B', 12, 10, 'Female', 103994],
       ['AsstProf', 'B', 3, 3, 'Female', 92000],
       ['AssocProf', 'B', 13, 10, 'Female', 103750],
       ['AssocProf', 'B', 14, 7, 'Female', 109650],
       ['Prof', 'A', 29, 27, 'Female', 91000],
       ['AssocProf', 'A', 26, 24, 'Female', 73300],
       ['Prof', 'A', 36, 19, 'Female', 117555],
       ['AsstProf', 'A', 7, 6, 'Female', 63100],
       ['Prof', 'A', 17, 11, 'Female', 90450],
       ['AsstProf', 'A', 4, 2, 'Female', 77500],
       ['Prof', 'A', 28, 7, 'Female', 116450],
       ['AsstProf', 'A', 8, 3, 'Female', 78500],
       ['AssocProf', 'B', 12, 9, 'Female', 71065],
       ['Prof', 'B', 24, 15, 'Female', 161101],
       ['Prof', 'B', 18, 10, 'Female', 105450],
       ['AssocProf', 'B', 19, 6, 'Female', 104542],
       ['Prof', 'B', 17, 17, 'Female', 124312],
       ['Prof', 'A', 28, 14, 'Female', 109954],
       ['Prof', 'A', 23, 15, 'Female', 109646]], dtype=object)

In [28]:
df.count

<bound method DataFrame.count of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [30]:
df.index

RangeIndex(start=0, stop=78, step=1)

In [32]:
df.max

<bound method NDFrame._add_numeric_operations.<locals>.max of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [36]:
df.shape[0]

78

In [39]:
df.shape[1]

6

In [42]:
df.columns.dtype

dtype('O')

In [50]:
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [46]:
df.mean()

<ipython-input-46-c61f0c8f89b5>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()

phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64

In [48]:
df.sample()

         rank discipline  phd  service     sex  salary
61  AssocProf          B   13       10  Female  103750

In [47]:
df.aggregate

<bound method DataFrame.aggregate of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [49]:
df.median()

<ipython-input-49-6d467abf240d>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median()

phd            18.5
service        14.5
salary     104671.0
dtype: float64

In [53]:
df.max()

rank            Prof
discipline         B
phd               56
service           51
sex             Male
salary        186960
dtype: object

In [55]:
df.all

<bound method NDFrame._add_numeric_operations.<locals>.all of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [58]:
df.duplicated

<bound method DataFrame.duplicated of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [59]:
df.ge

<bound method flex_comp_method_FRAME.<locals>.f of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [60]:
df.drop

<bound method DataFrame.drop of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [62]:
df.isnull().any()

rank          False
discipline    False
phd           False
service       False
sex           False
salary        False
dtype: bool

In [64]:
df.isnull().sum()

rank          0
discipline    0
phd           0
service       0
sex           0
salary        0
dtype: int64

In [69]:
df.isnull().values

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [70]:
df.add_prefix

<bound method NDFrame.add_prefix of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [72]:
df.from_records

In [75]:
df.salary.mean()

108023.78205128205

In [77]:
df.std()

<ipython-input-77-ce97bb7eaef8>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.std()

phd           12.498425
service       12.139768
salary     28293.661022
dtype: float64

In [80]:
df.head(50).mean()

<ipython-input-80-56442511a41d>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.head(50).mean()

phd            21.52
service        17.60
salary     113789.14
dtype: float64

In [82]:
d=df['salary']
d.mean()

108023.78205128205

In [87]:
df['rank']

0          Prof
1          Prof
2          Prof
3          Prof
4          Prof
        ...
73         Prof
74    AssocProf
75         Prof
76         Prof
77         Prof
Name: rank, Length: 78, dtype: object

In [91]:
d=df['phd']
d.describe()

count    78.000000
mean     19.705128
std      12.498425
min       1.000000
25%      10.250000
50%      18.500000
75%      27.750000
max      56.000000
Name: phd, dtype: float64

In [92]:
d.count()

78

In [93]:
d.mean()

19.705128205128204

In [96]:
  df.groupby(['sex'])

In [95]:
df.value_counts

<bound method DataFrame.value_counts of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [97]:
d.mean()

19.705128205128204

In [104]:
df_rank = df.groupby(['rank'])

In [108]:
df_rank.mean()

                 phd    service         salary
rank
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [109]:
df_rank.describe()

            phd                                                      service  \
          count       mean        std   min    25%   50%   75%   max   count
rank
AssocProf  13.0  15.076923   5.589597   9.0  12.00  13.0  19.0  26.0    13.0
AsstProf   19.0   5.052632   2.738079   1.0   3.50   4.0   7.0  11.0    19.0
Prof       46.0  27.065217  10.185834  12.0  19.25  24.5  34.5  56.0    46.0

                      ...              salary                               \
                mean  ...    75%   max  count           mean           std
rank                  ...
AssocProf  11.307692  ...  11.00  24.0   13.0   91786.230769  18571.183714
AsstProf    2.210526  ...   3.00   6.0   19.0   81362.789474   9381.245301
Prof       21.413043  ...  26.75  51.0   46.0  123624.804348  24850.287853


               min       25%       50%        75%       max
rank
AssocProf  62884.0   74830.0  103613.0  104542.00  119800.0
AsstProf   63100.0   74096.0   78500.0   91150.00   97032.0
Prof       57800.0  105112.5  123321.5  143512.25  186960.0

[3 rows x 24 columns]

In [114]:
A_avg = df.groupby(['sex'])

In [115]:
A_avg['salary'].mean()

sex
Female    101002.410256
Male      115045.153846
Name: salary, dtype: float64